apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-nginx-ingress
  namespace: platform-applications
  labels:
    app.kubernetes.io/name: enterprise-nginx
    app.kubernetes.io/part-of: enterprise-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-nginx
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
